name: Deploy Todo App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: docker build -t todo-app .
      
    - name: Test application
      run: |
        docker run -d -p 8080:80 --name test-container todo-app
        sleep 5
        curl -f http://localhost:8080 || exit 1
        docker stop test-container
        docker rm test-container
        
    - name: Success
      run: echo "✅ Application testée avec succès!"